language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzlOBKWRGpOmblzFtjAkXFuVY/KAzEDnDn1o9HDthrNfHAX4SwRkF1kC8noV5mKZAtg8FtKPVyI0sUur8AoxIEezF/mPAoq8IeCCdwd68PjUKPC6G1cWbhmhwGBp54p0Uy9QlMjbeT3dSjvTkU/woFT8hCDOxD4g3FXz5LOHqDNkcQ5RwcstOA5QfcI/w76QgzH7Y5z2FatdsK/1kXmgd9HyqbiStRfqDWVz6JlYX54h01mtRuUyK0zIZeYbkDYlZM245uOZyxqTrN2qXaHL6Mz2a4Rf6wdK4Fpb7HrwIA9qBkFTvSjziNWzsOijhzQlf50+mt24QyUBvSDq6ayj4EHcThTlTeYp0kSg5zZqsqhLXjxz//9PkvSaqPe9kUfuiLKteuwl3w41gYVbd+LvNcxG5Ltm96Qfbg11Ng9nN7BU8NCNAQR6GY6O5GqVXB1wg5R+LAPPSf+Y89KWTK5WtAEpReLTjGgBWTNxHc9AAid0Z2+31u9tyeAxM3QBwA0O8= root@1ce7f27761df
 app: CS3300Project
 run: "rake db:migrate"
 on:
  all_branches: true
